version: '3.7'

services:
  telegram-bot-api:
    container_name: telegram-bot-api
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: ${API_ID}
      TELEGRAM_API_HASH: ${API_HASH}
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - 8081:8081
  
  telegram-bot:
    container_name: telegram-bot
    build: .
    environment:
      API_HASH: ${API_HASH}
      API_ID: ${API_ID}
      SESSION_STRING: ${SESSION_STRING}
      BOT_TOKEN: ${BOT_TOKEN}
      API_HOST: "http://telegram-bot-api:8081"
    depends_on:
      - telegram-bot-api

volumes:
  telegram-bot-api-data:
