name: CD
on: [push, pull_request, workflow_dispatch]
jobs:
  deploy:
    name: "Deploy to aws"
    runs-on: ubuntu-latest
    steps:
      - name: "Configure SSH key"
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/aws
          chmod 600 ~/.ssh/aws
          cat >>~/.ssh/config <<END
          Host $IP_ADDR
            HostName $IP_ADDR
            User $USERNAME
            IdentityFile ~/.ssh/aws
            StrictHostKeyChecking no
          END
        env:
            SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
            IP_ADDR: ${{ secrets.IP_ADDR }}
            USERNAME: ${{ secrets.SERVER_USER }}
        
      - name: "Update repository"
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.IP_ADDR }} "rm -rf ${{ github.event.repository.name }}; git clone https://github.com/${{ github.repository }}.git"
      - name: "Build image"
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.IP_ADDR }} "cd ${{ github.event.repository.name }} && sudo docker rm -f ${{ github.event.repository.name }} && sudo docker build -t ${{ github.repository }} ."
      - name: "Deploy new version"
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.IP_ADDR }} "sudo docker rm -f ${{ github.repository }}; sudo docker run --name ${{ github.event.repository.name }} --restart always -e API_HASH="${{ secrets.API_HASH }}" -e API_ID="${{ secrets.API_ID }}" -e SESSION_STRING="${{ secrets.SESSION_STRING }}" -e BOT_TOKEN="${{ secrets.BOT_TOKEN }}" -d ${{ github.repository }}"
